dotnet ef dbcontext scaffold "Server=localhost;Trusted_Connection=True;Database=PH_Progress;TrustServerCertificate=True" Microsoft.EntityFrameworkCore.SqlServer ^
--context NavireoDbContext --force ^
--no-build				  ^
--table adr__Ewid		  ^
--table adr_Email		  ^
--table adr_Historia      ^
--table dks_Kasa		  ^
--table dok__Dokument	  ^
--table dok_Pozycja		  ^
--table dok_Vat			  ^
--table dbo.kh__Kontrahent	  ^
--table kh_AdresyDostawy  ^
--table kh_CechaKh		  ^
--table kh_Pracownik	  ^
--table pd__Podmiot		  ^
--table pd_Uzytkownik	  ^
--table tw__Towar 		  ^
--table tw_Parametr		  ^
--table tw_CechaTw		  ^
--table tw_Cena			  ^
--table tw_JednMiary	  ^
--table tw_KodKreskowy	  ^
--table tw_Komplet		  ^
--table tw_Stan			  ^
--table tw_ZdjecieTw	  ^
--table sl_Bank			  ^
--table sl_CechaKh		  ^
--table sl_CechaTw		  ^
--table sl_GrupaKh		  ^
--table sl_GrupaTw		  ^
--table sl_Kategoria	  ^
--table sl_Magazyn		  ^
--table sl_StawkaVAT	  ^
--table sl_Wlasny		  ^
--table nz__Finanse		  ^
--table IFx_ApiFormaPlatnosci			^
--table IFx_ApiPromocjaGrupa			^
--table IFx_ApiPromocjaGrupaZestaw		^
--table IFx_ApiPromocjaPozycja			^
--table IFx_ApiPromocjaPozycjaTowar		^
--table IFx_ApiPromocjaZestaw			^
--table IFx_ApiSposobDostawy			^
--table IFx_ApiUzytkownik				^
--table IFx_ApiUzytkownik_PoziomyCenowe	^
--table IFx_ApiUstawienia				^
--table IF_vwKontrahent